backend:
  name: git-gateway
  branch: master
  repo: laurelschwulst/pingpractice.org-eleventy

media_folder: "_site/assets/media"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Navigation Order", name: "nav_order", widget: "number" }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/page.njk",
            }
          - {
              label: "Permalink",
              name: "permalink",
              widget: "hidden",
              default: "/about/",
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Method"
        name: "method"
        file: "pages/method.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Method Text", name: "body", widget: "markdown" }
      - label: "App"
        name: "app"
        file: "pages/app.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "App Text", name: "body", widget: "markdown" }
      - label: "People"
        name: "people"
        file: "pages/people.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "People Text", name: "body", widget: "markdown" }
  - name: "transmissions"
    label: "Transmissions"
    folder: "transmissions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Transmission Text", name: "body", widget: "markdown" }
